---
- name: Disable hibernation (speeds up entering sleep mode).
  become: true
  shell: pmset -a hibernatemode 0
  changed_when: false

- name: Disable sudden motion sensor.
  become: true
  shell: pmset -a sms 0
  changed_when: false

- name: Disable recording of last access times.
  become: true
  copy:
    src: files/com.noatime.plist
    dest: /Library/LaunchDaemons/com.noatime.plist
    owner: root
    group: wheel

- name: Turn off network indexing
  become: true
  osx_defaults:
    domain: /Library/Preferences/com.apple.SpotlightServer.plist
    key: ExternalVolumesIgnore
    type: bool
    value: true
