---

- name: Disable local Time Machine snapshots.
  become: true
  shell: tmutil disablelocal
  changed_when: false

- name: Disable hibernation (speeds up entering sleep mode).
  become: true
  shell: pmset -a hibernatemode 0
  changed_when: false

- name: Disable sudden motion sensor.
  become: true
  shell: pmset -a sms 0
  changed_when: false

- name: Disable recording of last access times.
  become: true
  copy:
    src: files/com.noatime.plist
    dest: /Library/LaunchDaemons/com.noatime.plist
    owner: root
    group: wheel

- name: Get sleepimage stats.
  stat:
    path: /private/var/vm/sleepimage
  register: sleepimage

- name: Do we need to modify the sleepimage?
  set_fact:
    sleepimage_needs_to_be_recreated: (sleepimage.stat.exists and sleepimage.stat.size > 0) or not sleepimage.stat.exists

- name: Remove sleepimage.
  become: true
  file:
    path: /private/var/vm/sleepimage
    state: absent
  when: sleepimage_needs_to_be_recreated

- name: Touch sleepimage.
  become: true
  file:
    path: /private/var/vm/sleepimage
    state: touch
    owner: root
    group: wheel
    mode: 0600
  when: sleepimage_needs_to_be_recreated

- name: Set chflags on sleepimage.
  become: true
  shell: chflags uchg /private/var/vm/sleepimage
  when: sleepimage_needs_to_be_recreated

- name: Turn off network indexing
  become: true
  osx_defaults:
    domain: /Library/Preferences/com.apple.SpotlightServer.plist
    key: ExternalVolumesIgnore
    type: bool
    value: true
