---

- name: Enable tap to click for the login screen.
  osx_defaults:
    domain: "{{ item.domain|default(omit) }}"
    host: "{{ item.host|default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - host: currentHost
      domain: NSGlobalDomain
      key: com.apple.mouse.tapBehavior
      type: int
      value: 1
    - domain: NSGlobalDomain
      key: com.apple.mouse.tapBehavior
      type: int
      value: 1

- name: Enable tap to click for the current user.
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1
  register: tap_to_click_result
  ignore_errors: true

- name: Enable tap to click for the current user (retry).
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: true
  when: tap_to_click_result.failed is defined and tap_to_click_result.failed
