---

- name: Get account status.
  shell: 'mas account'
  register: mas_account_status
  failed_when: false
  check_mode: no
  changed_when: false

- name: Store sign in status.
  set_fact:
    mas_is_signed_in: "{{ 'Not signed in' not in mas_account_status.stdout }}"
