---

- name: Ensure yadm is installed.
  homebrew:
    state: latest
    name: [
      "yadm",
      "gpg" # required for encryption/decryption of dotfiles
    ]

- name: Fetch dotfiles.
  shell: yadm clone {{ yadm_repo_url }}
  args:
    creates: "~/.yadm/repo.git"
  register: yadm_clone_result

- name: Overwrite local changes, if needed.
  shell: yadm reset --hard
  when: yadm_clone_result.changed
