---

- name: Install rbenv.
  homebrew:
    name: ["rbenv", "ruby-build"]
    state: installed

- name: Install ruby 2.6.3.
  command: rbenv install 2.6.3 --skip-existing

- name: Set ruby 2.6.3 as the global ruby version.
  command: rbenv global 2.6.3

- name: Update Rubygems.
  command: gem update --system

- name: Update installed gems.
  command: gem update

- name: Install gems.
  gem:
    name: "{{ item }}"
    state: latest
  with_items:
    - cocoapods
    - git-up
